name: livedocpipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: edwarod/ubuntumono:version1.0
    env:
      SPECFLOW_PROJECT: PresentacionesInteractivas
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK 3.1.x
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test
      
      - name: Install SpecFlow LivingDoc generator
        run: dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

      - name: Generate LivingDoc documentation
        run: |
          export PATH="$PATH:/github/home/.dotnet/tools"
          livingdoc test-assembly ./$SPECFLOW_PROJECT/bin/Debug/netcoreapp3.1/$SPECFLOW_PROJECT.dll -t ./$SPECFLOW_PROJECT/bin/Debug/netcoreapp3.1/TestExecution.json --output ./docs

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: livingdoc # The branch the action should deploy to.
          folder: ./docs # The folder the action should deploy.